title: CSA final project
author: Yeha Kwon
email: ykwon1@ebnet.org
theme: minima
description: 

# social links
github_username:  ykwon1 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
